config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  mount Sidekiq::Web => "/sidekiq"
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  get "sign_in", to: "sign_in#new"
  post "sign_in", to: "sign_in#create"
  delete "sign_out", to: "sign_in#destroy"

  get "sign_up", to: "sign_up#new"
  post "sign_up", to: "sign_up#create"

  get "reset_password", to: "reset_password#new"
  post "reset_password", to: "reset_password#create"
  get "reset_password/edit", to: "reset_password#edit"
  patch "reset_password/update", to: "reset_password#update"

  root "home#index"
  post "async_action", to: "home#async_action"
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/removed_animal.rb
class RemovedAnimal < ApplicationRecord
end

app/models/request_logger.rb
class RequestLogger < ApplicationRecord
end

app/models/schedule_meeting.rb
class ScheduleMeeting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def generate_user_reset_token!
    self.reset_password_token = SecureRandom.urlsafe_base64
    self.reset_password_sent_at = Time.now
    save!
  end

  def reset_password_token_update_nil
    self.reset_password_token = nil
    self.reset_password_sent_at = nil
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include SessionHelper
  include ApplicationHelper
end

app/controllers/home_controller.rb
require "concurrent"

class HomeController < ApplicationController
  def index
  end

  def async_action
   # HelloJob.perform_at(10.seconds.from_now)
   # ReccuringMeetingsJob.perform_async()
   #  HomeHelper.start_time_intervel(2)
   #  sleep(5)
   #  HomeHelper.stop_time_intervel
   Log.blue("root dir  #{Dir[Rails.root.join("lib")]}   #{__dir__}")
   Log.green("file expande path #{File.expand_path("../Gemfile", __dir__)
   }")
  end

  def request_logs_information
  end
end

app/controllers/reset_password_controller.rb
class ResetPasswordController < ApplicationController
  def new
  end

  def create
    # Rails.logger("reset password created #{params}")
    begin
      @user =  User.find_by(email: params[:email])
      puts "================== #{@user}=====================  #{params}"
      if @user
        @user.generate_user_reset_token!
        UserMailer.password_reset(@user).deliver_now
        flash[:notice] = "Password reset email sent!"
        # redirect_to root_path, notice: "Password reset instructions sent to your email"
        respond_to do |format|
          format.html { redirect_to root_path, notice: "Reset email sent!" }
          format.turbo_stream { render turbo_stream: turbo_stream.replace("flash", partial: "shared/flash") }
        end
      else
         flash.now[:alert] = "Email Not Found"
         render :new
      end
    rescue Exception => e
       puts "+=+===============  #{e.message}"
      flash.now[:alert] = "Something went wrong  #{e.message}"
      render :new
    end
  end

  def edit
    @user =  User.find_by(reset_password_token: params[:token])
  end

  def update
    begin
      @user = User.find_by(reset_password_token: params[:token])

      if @user.nil?
        Rails.logger.error("No user found for token: #{params[:token]}")
        redirect_to reset_password_edit_path, alert: "Invalid or expired reset token" and return
      end

      Rails.logger.debug("User found: #{@user.email}, reset_password_sent_at: #{@user.reset_password_sent_at} ,  params:#{params}")

      if @user.reset_password_sent_at > 2.hours.ago
        if @user.update(reset_password_params)
          @user.reset_password_token_update_nil!
          redirect_to sign_in_path, notice: "Password has been reset!"
        else
          redirect_to reset_password_edit_path, alert: "Failed to update password"
        end
      else
        redirect_to reset_password_edit_path, alert: "Password reset has expired"
      end
    rescue => e
      Rails.logger.error("Error in reset password: #{e.message}   #{params[:user]}")
      redirect_to reset_password_edit_path, alert: "Something went wrong. Please try again."
    end
  end


  private
  def reset_password_params
    params.permit(:password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
end

app/controllers/sign_in_controller.rb
class SignInController < ApplicationController
  def new
    @user =  User.new
  end

  def create
    email  =  params[:email]
    password =  params[:password]
    user =  User.find_by(email: email)
    if user && user.authenticate(password)
      login(user)
    redirect_to root_path, notice: "Logged In successfully"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    logout()
    redirect_to sign_in_path,  notice: "Logged out successfully"
  end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  def new
    @user =  User.new
  end

  def create
    @user =  User.new(sign_up_params)
    if @user.save
      redirect_to root_path,  notice: "Account created successfully"
    else
      render :new
    end
  end

  private
  def sign_up_params
    params.require(:user).permit(:email,  :password,  :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def blue(t)
    puts "#{t}".colorize(:blue)
  end

  def red(t)
    puts "#{t}".colorize(:red)
  end

  def green(t)
    puts "#{t}", colorize(:green)
  end
end

app/helpers/home_helper.rb
module HomeHelper
  @time_intervel =  nil

  def self.start_time_intervel(delay)
    stop_time_intervel if  thread_running?
   @time_intervel =  Thread.new do
      sleep(delay)
      Log.green("time intervel started #{delay}")
    end
  end

  def self.stop_time_intervel
    if @time_intervel&.alive?
      @time_intervel.kill
      Log.green("Thread stopped")
    end
    @time_intervel = nil
  end

  def self.thread_running?
    @time_intervel&.alive? || false
  end
end

app/helpers/reset_password_helper.rb
module ResetPasswordHelper
end

app/helpers/session_helper.rb
module  SessionHelper
  def login(user)
    puts "SessionHelper #{session}"
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    session_user_id =  session[:user_id]
    @current_user ||=  User.find(session_user_id)
  end

  def logged_in?
    puts ("logged in  #{!@current_user}")
    !@current_user.nil?
  end
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>

<%= "Logged in #{logged_in?}"%>

<%= button_to  'sign out' ,  sign_out_path ,  method: :delete %>

<%=  button_to   "sidekiq check",  async_action_path,  method: :post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Custom Login" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/reset_password/edit.html.erb
<%= form_with  url: reset_password_update_path , method: :patch do  |f| %>
    <%= f.hidden_field :token ,  value: params[:token] %>
  <div>
    <%=  f.label :password,   "New password"%> 
    <%=  f.password_field :password   %> 
  </div>
  <div>
    <%=  f.label :password_confirmation,   "Confirm password"%> 
    <%=  f.password_field :password_confirmation   %> 
  </div>
  <div>
    <%=  f.submit "Reset Password" %> 
  </div>
<% end %>

app/views/reset_password/new.html.erb
<h1>Reset Password</h1>

<%= form_with url: reset_password_path do |form| %>
  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.submit "Reset Password" ,  method: :post  %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div id="flash-messages">
    <% flash.each do |type, message| %>
      <div class="flash <%= type %>"><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/sign_in/new.html.erb
<h1>Sign In</h1>

<%= form_with url: sign_in_path do |form| %>
  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.submit "Sign In" %>
<% end %>

<%= link_to "Forgot password?", reset_password_path %>
<br/>
<%= link_to "Sign up" ,  sign_up_path %>

app/views/sign_up/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, url: sign_up_path do |form| %>
  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "Create Account" %>
<% end %>